### PR TITLE
Fix parse integer overflow error message

### LINKED ISSUE #136: Wrong error output while overflowing index
image

### LINKED ISSUE #154: [PE-D][Tester A] Inputting an overflow number as an index
As shown below, by inputting an extremely large number. The error message thrown is Invalid Command format. However, in this scenario, the error message should be "The application index provided is invalid" specified when I input an integer that is out of bound. This could potentially confuse users on how to correct their command.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: GarethOng/ped#4

### PR DESCRIPTION
**Pull request by teekaytai**
Fixes the message that is shown if a user enters a valid index that overflows an int.
Now the message shown is "The index provided is too big to process."
The behaviour in any other case remains the same.

This fixes #136 and fixes #154

### CODE REVIEW

File: src/test/java/seedu/application/commons/util/StringUtilTest.java [hunk 1]
```diff
@@ -38,13 +38,46 @@ public void isNonZeroUnsignedInteger() {
...
+
+        // EP: numbers with white space
+        assertFalse(StringUtil.isNonZeroUnsignedBigInteger(" 10 ")); // Leading/trailing spaces
+        assertFalse(StringUtil.isNonZeroUnsignedBigInteger("1 0")); // Spaces in the middle
+
+        // EP: valid numbers, should return true
+        assertTrue(StringUtil.isNonZeroUnsignedBigInteger("1")); // Boundary value
+        assertTrue(StringUtil.isNonZeroUnsignedBigInteger("10"));
+        // number larger than Integer.MAX_VALUE also return true
+        assertTrue(StringUtil.isNonZeroUnsignedBigInteger(Long.toString((long) Integer.MAX_VALUE + 1)));
```
Comment (jhchee18) [inline src/test/java/seedu/application/commons/util/StringUtilTest.java:79]: does `isNonZeroUnsignedBigInteger` take into account for `Integer.MIN_VALUE - 1`?

**Review by jhchee18 — COMMENTED** [review]
Looks good 👍 Just one qn inside

**Review by eesung00 — COMMENTED** [review]
Had a brief look, LGTM 👍

File: src/test/java/seedu/application/commons/util/StringUtilTest.java (hunk 1 above)
Comment (teekaytai) [reply src/test/java/seedu/application/commons/util/StringUtilTest.java:79]: Yup, if the input is a negative number then `isNonZeroUnsignedBigInteger` will also return false, so the invalid command format message will be displayed. The various command usage messages will explain that the index needs to be a positive integer
