### PR TITLE
Fix remind list

### LINKED ISSUE #126: Ui Exception
After interview sort is implemented, updating list with any command will cause this exception.

image

### LINKED ISSUE #172: [PE-D][Tester A] Remind feature not working as intended
According to the user guide, reminds does the following:
Shows a list of all upcoming interviews within the next 1 week, sorted by interview date and time.

As of report 28/10/2022 5:00 pm, the interviews shown below i1 and i2 are within a week from the current date and time.

However, upon entering the remind command. It creates a reminder for an interview more than a week away  and doesn't show the interview that are upcoming.

This is fatal feature flow that might result in users missing their interviews.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: GarethOng/ped#6

### LINKED ISSUE #178: [PE-D][Tester C] Remind Command error
The Remind command incorrectly shows interview dates that are beyond 1 week period stated in the UG. 

In this example, the window shows me interviews in 2024.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: maxtance/ped#14

### LINKED ISSUE #179: [PE-D][Tester B] No interviews shown on remind window
Did a testing with dates 1 day, 2day and 1week after current date of testing. No interviews were shown on the remind window. :(

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: jovitaanderson/ped#9

### PR DESCRIPTION
**Pull request by teekaytai**
The bug was caused by a momentary inclusion of applications with no interview into the remind list and the `InterviewComparator` not handling applications with no interview safely.

The code has been refactored to help ensure the remind list is correctly updated.
Here's a summary of the changes:

- The remind list now properly observes the underlying application book's list, so there's no need to manually update it using `updateApplicationListWithInterview` 
- The list is initialised with the `UpcomingInterviewPredicate` immediately, so there's no need to wait for a remind command to set it
- `InterviewComparator` now checks for the presence of the interview first (even though this should not be necessary now) to make the code more defensive

This fixes #172, fixes #178 and fixes #179
This also fixes #126

### CODE REVIEW

**Review by jhchee18 — COMMENTED** [review]
Thanks for the refactoring! But, in this way the interview list in the archived application list will not get updated to those archived application as we intended tho.

image

**Comment by teekaytai** [comment]
> But, in this way the interview list in the archived application list will not get updated to those archived application as we intended tho.

Oh yeah, that's my bad. I'll tweak the code a bit. Thanks for spotting!

**Review by jhchee18 — COMMENTED** [review]
Thanks for the quick fix! LGTM 👍

File: src/main/java/seedu/application/logic/LogicManager.java [hunk 1]
```diff
@@ -72,7 +72,7 @@ public ObservableList<Application> getApplicationListWithInterview() {
 
     @Override
     public ObservableList<Application> getFilteredApplicationListWithUpcomingInterview() {
```
Comment (jolynloh) [inline src/main/java/seedu/application/logic/LogicManager.java]:
```suggestion
    public ObservableList<Application> getApplicationListWithUpcomingInterview() {
```

File: src/test/java/seedu/application/logic/commands/RemindCommandStub.java [hunk 2]
```diff
@@ -20,13 +19,9 @@ public class RemindCommandStub extends Command {
 
     public static final String SHOWING_REMIND_MESSAGE = "Opened reminder window.";
 
-    private static final UpcomingInterviewPredicateStub UPCOMING_INTERVIEW_PREDICATE =
-            new UpcomingInterviewPredicateStub();
-
```
Comment (jolynloh) [inline src/test/java/seedu/application/logic/commands/RemindCommandStub.java:25]: ah so then there's no longer a need for `RemindCommandStub` since the only difference between this stub and `RemindCommand` is that this uses the `UpcomingInterviewPredicateStub`, which is no longer the case?

**Review by jolynloh — COMMENTED** [review]
LGTM! Thanks for helping to rectify this issue with remind which has been bugging me for days and for tidying up the overall code logic 😃

File: src/test/java/seedu/application/logic/commands/RemindCommandStub.java (hunk 2 above)
Comment (teekaytai) [reply src/test/java/seedu/application/logic/commands/RemindCommandStub.java:25]: That's a good point. Actually it is a bit odd to be stubbing the class to be tested in the first place. Usually stubs are for replacing the dependencies of the class to be tested. Maybe after this PR is merged you can help replace both stubs with the original classes if you'd like? You can design the test cases to be based off the current date and time so that they always pass/fail the predicate no matter when they are run

Comment (jolynloh) [reply src/test/java/seedu/application/logic/commands/RemindCommandStub.java:25]: yepp makes sense I'll do that after this is merged~

The rationale for the stubs initially was that the remind command depends on the 'current date and time' so I used the stub to fix a specific date/time. But now there's no need for it since I can just base it off the current date/time
