### PR TITLE
Fix Bug

### LINKED ISSUE #126: Ui Exception
After interview sort is implemented, updating list with any command will cause this exception.

image

### LINKED ISSUE #148: [PE-D][Tester B] No example in messageBox
Example of how to use interview command is not included in message box

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: jovitaanderson/ped#2

### LINKED ISSUE #176: [PE-D][Tester C] UG: May want to state that archiving an application will archive the interview as well
No details provided by bug reporter.

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: maxtance/ped#12

### LINKED ISSUE #177: [PE-D][Tester C] Error message is not specific for Archive command
After `list-archive`, executing a `archive 3` when there are only 1 application results in the error message: 

However, the command error should be along the lines of "command can only be used in list view". 

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: maxtance/ped#13

### LINKED ISSUE #180: [PE-D][Tester A] Attempting to archive a valid index after list-archive
Upon performing the sequence of "list-archive" -> "archive 4". The error message "The application index provided is invalid" was thrown. This is not an ideal error message as it is valid index given that I have 10 applications. In this scenario, the error message provided should guide users by informing them to perform "list" followed by "archive x" where x is their desired index. This will lead to less confusion when using the application.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: GarethOng/ped#7

### PR DESCRIPTION
**Pull request by eesung00**
Resolve #180 and #177 by updating error message.
- Also updated user guide in find command to improve clarity

Resolve #126 by checking present of interview before getting

Resolve #176 by adding the description in UG

Resolve #148 by using a separate line for examples, considering that scrolling down vertically is easier than horizontally
- minor text will be shown also so that user are less likely to miss the example.
image

### CODE REVIEW

File: src/main/java/seedu/application/commons/core/Messages.java [hunk 1]
```diff
@@ -8,11 +8,9 @@ public class Messages {
     public static final String MESSAGE_UNKNOWN_COMMAND = "Unknown command";
     public static final String MESSAGE_INVALID_COMMAND_FORMAT = "Invalid command format! \n%1$s";
     public static final String MESSAGE_INVALID_APPLICATION_DISPLAYED_INDEX = "The application index provided"
-            + " is invalid";
-    public static final String MESSAGE_INVALID_ARCHIVE_APPLICATION_DISPLAYED_INDEX = "The application index provided"
-            + " in archive list is invalid";
-    public static final String MESSAGE_INVALID_INTERVIEW_DISPLAYED_INDEX = "The interview index provided"
-            + " is invalid";
+            + " is invalid\n" + "Please note that the index is always referring to the last shown list below";;
```
Comment (jhchee18) [inline src/main/java/seedu/application/commons/core/Messages.java]:
```suggestion
            + " is invalid\n" + "Please note that the index refers to the last shown list below";
```

File: src/main/java/seedu/application/commons/core/Messages.java [hunk 2]
```diff
@@ -8,11 +8,9 @@ public class Messages {
...
+    public static final String MESSAGE_INVALID_INTERVIEW_DISPLAYED_INDEX = "The interview index provided is invalid\n"
+            + "Please note that the index is always referring to the last shown list below";
```
Comment (jhchee18) [inline src/main/java/seedu/application/commons/core/Messages.java]:
```suggestion
            + "Please note that the index refers to the last shown list below";
```

File: src/main/java/seedu/application/logic/commands/ArchiveCommand.java [hunk 3]
```diff
@@ -28,6 +27,13 @@ public class ArchiveCommand extends Command {
             + "Example: 1) " + ListCommand.COMMAND_WORD + "\n"
             + "               2) " + COMMAND_WORD + " 1";
 
+    public static final String MESSAGE_INVALID_INDEX_ARCHIVE = "The application index provided is invalid!\n"
+            + "Please note that the index is always referring to the last shown list below\n"
```
Comment (jhchee18) [inline src/main/java/seedu/application/logic/commands/ArchiveCommand.java]:
```suggestion
            + "Please note that the index refers to the last shown list below.\n"
```

File: src/main/java/seedu/application/logic/commands/RetrieveCommand.java [hunk 4]
```diff
@@ -21,11 +20,20 @@ public class RetrieveCommand extends Command {
...
-    public static final String MESSAGE_APPLICATION_IS_NOT_ARCHIVE = "The application by the index is not archived.\n"
+    public static final String MESSAGE_APPLICATION_IS_NOT_ARCHIVE = "The application provided by the"
+            + " index is not archived.\n"
             + "Please switch to archive list using <list-archive> command before using <retrieve> command.\n"
             + "Example: 1) " + ListArchiveCommand.COMMAND_WORD + "\n"
             + "              2) " + COMMAND_WORD + " 1";
 
+    public static final String MESSAGE_INVALID_APPLICATION_DISPLAYED_INDEX_RETRIEVE = "The application index "
+            + "provided is invalid!\n"
+            + "Please note that the index is always referring to the last shown list below\n"
```
Comment (jhchee18) [inline src/main/java/seedu/application/logic/commands/RetrieveCommand.java]:
```suggestion
            + "Please note that the index refers to the last shown list below.\n"
```

File: src/main/java/seedu/application/logic/commands/RetrieveCommand.java [hunk 5]
```diff
@@ -21,11 +20,20 @@ public class RetrieveCommand extends Command {
...
+            + "To ensure the retrieve function works, please use <list-archive> command to show the current"
+            + " archived application list\n"
```
Comment (jhchee18) [inline src/main/java/seedu/application/logic/commands/RetrieveCommand.java]:
```suggestion
            + " archived application list.\n"
```

File: src/main/java/seedu/application/logic/commands/ArchiveCommand.java [hunk 6]
```diff
@@ -28,6 +27,13 @@ public class ArchiveCommand extends Command {
...
+            + "To ensure the archive function works, please use <list> command to show the current"
+            + " unarchived application list\n"
```
Comment (jhchee18) [inline src/main/java/seedu/application/logic/commands/ArchiveCommand.java:33]:
```suggestion
            + " unarchived application list.\n"
```

File: src/main/java/seedu/application/model/ModelManager.java [hunk 7]
```diff
@@ -351,6 +351,11 @@ public void updateApplicationListWithInterview() {
         applicationsWithInterview.clear();
         applicationsWithInterview.addAll(filteredApplications);
         applicationsWithInterview.removeIf(application -> application.getInterview().isEmpty());
+        for (Application app : applicationsWithInterview) {
+            if (!app.hasInterview()) {
+                assert false;
+            }
```
Comment (jhchee18) [inline src/main/java/seedu/application/model/ModelManager.java]:
```suggestion
            assert app.hasInterview();
```

**Review by jhchee18 — COMMENTED** [review]
Only a few fixes. Overall looks good. 👍

File: docs/UserGuide.md [hunk 8]
```diff
@@ -159,6 +159,7 @@ Format: `find KEYWORD [MORE_KEYWORDS]`
 * The keywords are only searched for inside the applications' companies and positions.
 * Only full words will be matched e.g. `ByteDance` will not match `ByteDances`.
 * Applications matching at least one keyword will be returned (i.e. `OR` search). e.g. `Google Shopee` will match `Shopee HQ` and `Google Singapore`.
+* `find` command is also able to search for archived application and use `retrieve` command on the last shown list. However, please ensure that the index provided is within the last shown list and the selected application is archived.
```
Comment (jolynloh) [inline docs/UserGuide.md]:
```suggestion
* `find` command is also able to search for archived applications with matching keywords and `retrieve` command can be used on the last shown list. However, please ensure that the index provided is within the last shown list and the selected application is archived.
```

File: src/main/java/seedu/application/model/application/interview/InterviewComparator.java [hunk 9]
```diff
@@ -9,16 +10,26 @@
...
+            int compareTime = i1.get().getInterviewTime().value
+                    .compareTo(i2.get().getInterviewTime().value);
+            if (compareDate == 0) {
+                return compareTime;
+            } else {
+                return compareDate;
+            }
         } else {
-            return compareDate;
+            assert false : "Interview should exist while using comparator to sort";
```
Comment (jolynloh) [inline src/main/java/seedu/application/model/application/interview/InterviewComparator.java]: I guess for now it seems that this is not always true with the bug that @teekaytai spotted?

**Review by jolynloh — COMMENTED** [review]
LGTM! Thanks for helping to resolve the issues 👍

File: src/main/java/seedu/application/model/application/interview/InterviewComparator.java (hunk 9 above)
Comment (eesung00) [reply src/main/java/seedu/application/model/application/interview/InterviewComparator.java]: Hmmm, I'm not sure how the code will change after he fix the bug but according to the current implementation the interview should exist. After checking whether the interview isPresent() in the Optional the UI exception in #126 will only not appear. 

Anyway if it doesn't exist it should also be our problem right because we should check the existence of interview before trying to sort it with the comparator? I'm putting this assertion by judging it would be our problem if using the interview comparator before checking its existence.

Comment (jolynloh) [reply src/main/java/seedu/application/model/application/interview/InterviewComparator.java]: oh yeah sorry I meant it as a comment but yup the logic makes sense here, there should be interviews to compare if we are using the comparator

Comment (eesung00) [reply src/main/java/seedu/application/model/application/interview/InterviewComparator.java]: Oh nvm haha, actually I just checked the modified version of InterviewComparator and it actually no need this assert anymore as it handles the case where no interview is in the application.
