### PR TITLE
Fix edit command when application has interview

### LINKED ISSUE #170: [PE-D][Tester E] Interview disappears when name of application is changed
As per UG for `edit`, "Changes to the company name and the position will also be reflected in the interview list."

The actual behaviour is that the interview just disappeared :(

Same problem is present when position is edited.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: waynezsy/ped#7

### PR DESCRIPTION
**Pull request by teekaytai**
The bug was that the code tried to check for the presence of the interview _on the newly created editedApplication_ to decide whether to add an interview to it.

This fixes #170

### CODE REVIEW

File: src/main/java/seedu/application/logic/commands/EditCommand.java [hunk 1]
```diff
@@ -89,17 +88,9 @@ public CommandResult execute(Model model) throws CommandException {
             throw new CommandException(MESSAGE_DUPLICATE_APPLICATION);
         }
 
-        Optional<Interview> interview = editedApplication.getInterview();
```
Comment (eesung00) [inline src/main/java/seedu/application/logic/commands/EditCommand.java:92]: Oh yeah cuz editedApplication will always dun have interview. Nice fix 👍

**Review by eesung00 — COMMENTED** [review]
LGTM 👍

**Review by jhchee18 — COMMENTED** [review]
LGTM!
