### PR TITLE
Fix unknown prefix in input

### LINKED ISSUE #209: Misleading error messages when incorrect prefix used
When an optional prefix uses the wrong letter(s), it can give rise to misleading errors.

An example would be `edit 1 ct/91234567 em/internships@shopee.com`

Here the `em/` prefix should have been `e/`. Since prefixes to the edit command are optional, the invalid command format is not shown. Instead, the whole `91234567 em/internships@shopee.com` gets parsed as the contact number, giving rise to the "contact numbers should only contain numbers" error. This behaviour would be surprising to the user who would expect `91234567` to be used as the contact number.

We have 2 options. One is change the parser behaviour to ignore/error on incorrect prefixes, which could have the side effect of changing what happens when a user attempts to use slashes in text. Alternatively, we can add a note to the UG that incorrect prefixes get parsed as regular text.

### PR DESCRIPTION
**Pull request by eesung00**
Resolved #209 by extracting the prefixes from the argument. Then check if the prefixes extract fits the command

* No regression bug spotted as all automatic tests passed after implementation (For now)
* Does not applicable with the command that does not take in argument (`list`, `undo`, `redo`, etc)
* Not applicable to `FindCommand` (does not limit the keywords style/pattern in the original implementation)

For the `sort` feature
image

### CODE REVIEW

File: src/test/java/seedu/application/model/application/UpcomingInterviewPredicateTest.java [hunk 1]
```diff
@@ -41,14 +41,36 @@ public void test_isUpcomingInterview_returnsTrue() {
...
+        //Take account of time is 2359
+        if (LocalTime.now().plusMinutes(1).equals(LocalTime.of(0, 0))) {
+            aMinuteLaterApplication = new ApplicationBuilder().withInterview(
+                    new InterviewBuilder().withInterviewDate(LocalDate.now().plusDays(1))
+                            .withInterviewTime(LocalTime.of(0, 0)).build()).build();
+        } else {
+            aMinuteLaterApplication = new ApplicationBuilder().withInterview(
+                    new InterviewBuilder().withInterviewDate(LocalDate.now())
+                            .withInterviewTime(LocalTime.now().plusMinutes(1)).build()).build();
+        }
```
Comment (teekaytai) [inline src/test/java/seedu/application/model/application/UpcomingInterviewPredicateTest.java]: I think this might still go wrong because `LocalTime` also stores seconds, so the 2359 plus one minute may not `equal` midnight. How about using `LocalDateTime` instead?
```suggestion
        LocalDateTime aMinuteLater = LocalDateTime.now().plusMinutes(1);
        Application aMinuteLaterApplication = new ApplicationBuilder().withInterview(
                new InterviewBuilder().withInterviewDate(aMinuteLater.toLocalDate()),
                        .withInterviewTime(aMinuteLater.toLocalTime()).build()).build();
```

File: src/test/java/seedu/application/model/application/UpcomingInterviewPredicateTest.java [hunk 2]
```diff
@@ -41,14 +41,36 @@ public void test_isUpcomingInterview_returnsTrue() {
...
+
+        if (isNextDayAfterAnHour || isExactlyNextDayAfterAnHour) {
+            anHourLaterApplication = new ApplicationBuilder().withInterview(
+                    new InterviewBuilder().withInterviewDate(LocalDate.now().plusDays(1))
+                            .withInterviewTime(LocalTime.now().plusHours(1)).build()).build();
+        } else {
+            anHourLaterApplication = new ApplicationBuilder().withInterview(
+                    new InterviewBuilder().withInterviewDate(LocalDate.now())
+                            .withInterviewTime(LocalTime.now().plusHours(1)).build()).build();
+        }
```
Comment (teekaytai) [inline src/test/java/seedu/application/model/application/UpcomingInterviewPredicateTest.java]:
```suggestion
        LocalDateTime anHourLater = LocalDateTime.now().plusHours(1);
        Application anHourLaterApplication = new ApplicationBuilder().withInterview(
                new InterviewBuilder().withInterviewDate(anHourLater.toLocalDate()),
                        .withInterviewTime(anHourLater.toLocalTime()).build()).build();
```

**Review by teekaytai — COMMENTED** [review]
Haven't studied it enough to fully understand how/if it works, but it seems like the checks only protect prefixes to do with the model? The command `sort by/company r/` is able to sneak through the checks (the resulting sort is reverse chronological, not by company).
Thanks for putting in the time to work on this!

File: src/test/java/seedu/application/model/application/UpcomingInterviewPredicateTest.java (hunk 1 above)
Comment (eesung00) [reply src/test/java/seedu/application/model/application/UpcomingInterviewPredicateTest.java]: Thanks for the suggestion! didn't know LocalDateTime can do this 😅

**Comment by eesung00** [comment]
> Haven't studied it enough to fully understand how/if it works, but it seems like the checks only protect prefixes to do with the model? The command `sort by/company r/` is able to sneak through the checks (the resulting sort is reverse chronological, not by company). Thanks for putting in the time to work on this!

Yeah true I missed that case. But for the commands that only depends on one word, do we want to protect them from unknown prefix too? (e.g. `list`, `undo`, `remind`, etc)

**Comment by teekaytai** [comment]
Whatever is easier I suppose. If convenient, I suppose making things consistent is better, so we can protect the one word commands too. If we do that, we gotta remember to update the UG too (the part that says extraneous parameters are ignored)

File: src/main/java/seedu/application/logic/parser/ArchiveCommandParser.java [hunk 3]
```diff
@@ -6,18 +6,27 @@
...
+    private static final int NUMBER_OF_PREFIX_REQUIRED = 0;
+
     /**
      * Parses the given {@code String} of arguments in the context of the ArchiveCommand
      * and returns a ArchiveCommand object for execution.
      * @throws ParseException if the user input does not conform the expected format.
      */
     public ArchiveCommand parse(String args) throws ParseException {
+
+        if (ArgumentTokenizer.prefixFound(args).size() > NUMBER_OF_PREFIX_REQUIRED) {
```
Comment (teekaytai) [inline src/main/java/seedu/application/logic/parser/ArchiveCommandParser.java]: Perhaps `!ArgumentTokenizer.prefixFound(args).isEmpty()` might be a more straightforward way of writing this? Same comment for other parsers with no prefixes like `delete`

File: src/main/java/seedu/application/logic/parser/ArgumentTokenizer.java [hunk 4]
```diff
@@ -28,6 +34,24 @@ public static ArgumentMultimap tokenize(String argsString, Prefix... prefixes) {
...
 
+    //@@author eesung00-reused
+    //Reused from https://stackoverflow.com/questions/4662215/how-to-extract-a-substring-using-regex
+    // with minor modifications
+    /**
+     * Returns a List of prefixes found from the arguments.
+     * @param argsString Arguments string of the form: {@code preamble <prefix>value <prefix>value ...}
+     * @return           List of Prefixes found.
+     */
+    public static Set<Prefix> prefixFound(String argsString) {
```
Comment (teekaytai) [inline src/main/java/seedu/application/logic/parser/ArgumentTokenizer.java]: Maybe can rename this to sound more like a verb, something like `findPrefixes`

File: src/main/java/seedu/application/logic/parser/ArgumentTokenizer.java [hunk 5]
```diff
@@ -28,6 +34,24 @@ public static ArgumentMultimap tokenize(String argsString, Prefix... prefixes) {
         return extractArguments(argsString, positions);
     }
 
+    //@@author eesung00-reused
+    //Reused from https://stackoverflow.com/questions/4662215/how-to-extract-a-substring-using-regex
+    // with minor modifications
+    /**
+     * Returns a List of prefixes found from the arguments.
+     * @param argsString Arguments string of the form: {@code preamble <prefix>value <prefix>value ...}
+     * @return           List of Prefixes found.
```
Comment (teekaytai) [inline src/main/java/seedu/application/logic/parser/ArgumentTokenizer.java]:
```suggestion
     * @return           Set of Prefixes found.
```

File: src/main/java/seedu/application/logic/parser/ArgumentTokenizer.java [hunk 6]
```diff
@@ -28,6 +34,24 @@ public static ArgumentMultimap tokenize(String argsString, Prefix... prefixes) {
         return extractArguments(argsString, positions);
     }
 
+    //@@author eesung00-reused
+    //Reused from https://stackoverflow.com/questions/4662215/how-to-extract-a-substring-using-regex
+    // with minor modifications
+    /**
+     * Returns a List of prefixes found from the arguments.
```
Comment (teekaytai) [inline src/main/java/seedu/application/logic/parser/ArgumentTokenizer.java]:
```suggestion
     * Returns a Set of prefixes found from the arguments.
```

File: src/main/java/seedu/application/logic/parser/Parser.java [hunk 7]
```diff
@@ -8,6 +8,9 @@
  */
 public interface Parser<T extends Command> {
 
+    String MESSAGE_UNKNOWN_PREFIX_FOUND = "Unknown prefix detected in the command, please "
```
Comment (teekaytai) [inline src/main/java/seedu/application/logic/parser/Parser.java]: A bit nitpicky but I feel "unexpected" might be a better word to use here
```suggestion
    String MESSAGE_UNEXPECTED_PREFIX_FOUND = "Unexpected prefix detected in the command, please "
```

File: src/main/java/seedu/application/model/application/Position.java [hunk 8]
```diff
@@ -3,6 +3,7 @@
 import static java.util.Objects.requireNonNull;
 import static seedu.application.commons.util.AppUtil.checkArgument;
 
+
```
Comment (teekaytai) [inline src/main/java/seedu/application/model/application/Position.java]: Looks like a stray line break was added here as well as in `Tag`

**Review by teekaytai — COMMENTED** [review]
Yup I think this implementation should be safe! You'd probably need a really unnatural input to get a weird result.
I've left some code quality suggestions.
Also wanna check if leaving out the FindCommandParser was intended?
Thanks again for the effort put into this!

File: src/main/java/seedu/application/logic/parser/ArchiveCommandParser.java (hunk 3 above)
Comment (eesung00) [reply src/main/java/seedu/application/logic/parser/ArchiveCommandParser.java]: Yes, I agree, thanks for the suggestion! 👍

**Comment by eesung00** [comment]
> Yup I think this implementation should be safe! You'd probably need a really unnatural input to get a weird result. I've left some code quality suggestions. Also wanna check if leaving out the FindCommandParser was intended. Thanks again for the effort put into this!

I'm just thinking that implementing the restriction on the find command is not very crucial also since it will just see the prefix as a keyword, do you think we should restrict it?

**Comment by teekaytai** [comment]
Fair enough, I guess we can safely exclude the find command parser from this 👌

**Comment by eesung00** [comment]
> Fair enough, I guess we can safely exclude the find command parser from this 👌

Alright, let me add some test cases then I'll merge it
